# Generated by Django 3.1.1 on 2021-04-27 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patoa.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patnof', models.CharField(max_length=11, null=True, validators=[patoa.validators.validate_patnof])),
                ('claim_list', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
