# Generated by Django 3.1.1 on 2021-04-27 23:28

from django.db import migrations, models
import patoa.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='patnof',
            field=models.IntegerField(null=True, validators=[patoa.validators.validate_patnof]),
        ),
    ]
